exclude = [
  "@ref",
  "@cite",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://tulipaenergy.github.io/TulipaBuilder.jl/stable$",
  "^https://blog.esciencecenter.nl",
  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
