name = "TulipaBuilder"
uuid = "05fe4dc7-9a58-53a4-b912-b5673d74e816"
version = "0.2.0"
authors = ["Abel Soares Siqueira"]

[workspace]
projects = ["test", "docs", "examples"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
TulipaEnergyModel = "5d7bd171-d18e-45a5-9111-f1f11ac5d04d"
TulipaIO = "7b3808b7-0819-42d4-885c-978ba173db11"

[compat]
DataFrames = "1.7.0"
DuckDB = "1.3.1"
Graphs = "1.13.0"
MetaGraphsNext = "0.7.3, 0.8"
TulipaEnergyModel = "0.17, 0.18, 0.19, 0.20"
TulipaIO = "0.5.0"
julia = "1.10"
