# Don't forget to run
#
#     pkg> dev ..
#
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
TulipaBuilder = "05fe4dc7-9a58-53a4-b912-b5673d74e816"

[compat]
Documenter = "1"

[sources]
TulipaBuilder = { path = ".." }
